Add simple implementation of roles
AlexeyShirinkin/EducationalPlatform pull request #7
Opened 2021-10-03 17:23 UTC by AlexeyShirinkin

2021-10-03 17:23 UTC, AlexeyShirinkin commented
Егор, сделай плиз миграцию, у меня чет не выходит

2021-10-04 15:54 UTC, Egor1712 requested changes

2021-10-04 15:54 UTC, Egor1712 commented on EducationalPlatform/Attributes/AuthorizationAttribute.cs
> +            if (user.Identity == null || !user.Identity.IsAuthenticated || roles.Any(x => !user.IsInRole(x)))
Может user.HasRole?

2021-10-04 15:54 UTC, Egor1712 commented on EducationalPlatform/Attributes/AuthorizationAttribute.cs
> +        public AuthorizationAttribute(params string[] roles) : base(typeof(AuthorizationFilter))
Почему бы не разделить атрибуты на Authorization и RequireRole, все таки это разная логика

2021-10-04 15:54 UTC, Egor1712 commented on RepositoriesLibrary/Models/User.cs
> +        public string Role { get; set; }
Несколько ролей может быть

2021-10-04 15:54 UTC, Egor1712 commented on RepositoriesLibrary/Models/User.cs
> +        public string Role { get; set; }
Еще наверное нужно энамом делать, чтобы понимать где какая роль

2021-10-04 15:54 UTC, Egor1712 commented on EducationalPlatform/Controllers/UserController.cs
> +    [Authorization("admin")]
Вот, лучше бы разделить на два разных атрибута, и еще энам туда и ваще кайф

2021-10-04 15:54 UTC, Egor1712 commented on EducationalPlatform/Controllers/AccountController.cs
> +            //кинуть исключение
Можно накинуть ограничение в базе или в первичный ключ добавить логин

2021-10-04 15:54 UTC, Egor1712 commented on EducationalPlatform/Attributes/AuthorizationAttribute.cs
>                  context.Result = new UnauthorizedResult();
Леха: работает в портальных сервисах
Также Леха: бросаем UnAuthorized когда у нас по роли метод не доступен)))))))))))
Прости, не удержался)) Надо бы Forrbidden кидать когда роль не подходит

2021-10-04 15:55 UTC, Egor1712 commented on EducationalPlatform/Attributes/AuthorizationAttribute.cs
> +        public AuthorizationAttribute(params string[] roles) : base(typeof(AuthorizationFilter))
И еще мб нам накинуть на всю апишку атрибут Authorization?

2021-10-05 05:25 UTC, AlexeyShirinkin commented on EducationalPlatform/Attributes/AuthorizationAttribute.cs
> +            if (user.Identity == null || !user.Identity.IsAuthenticated || roles.Any(x => !user.IsInRole(x)))
Нет такого метода

2021-10-05 08:42 UTC, AlexeyShirinkin commented on EducationalPlatform/Attributes/AuthorizationAttribute.cs
> +        public AuthorizationAttribute(params string[] roles) : base(typeof(AuthorizationFilter))
На AccountController?

2021-10-05 08:43 UTC, AlexeyShirinkin commented on RepositoriesLibrary/Models/User.cs
> +        public string Role { get; set; }
А как enum[] в базе будет?
Я прост не могу сделать миграцию из за непонятных мне ошибок, хотел вручную поменять

2021-10-05 08:43 UTC, AlexeyShirinkin commented on EducationalPlatform/Attributes/AuthorizationAttribute.cs
>                  context.Result = new UnauthorizedResult();
Да реально я даун, поправлю

2021-10-05 09:03 UTC, Egor1712 commented on RepositoriesLibrary/Models/User.cs
> +        public string Role { get; set; }
Они будут  как массив стрингов

2021-10-05 09:03 UTC, Egor1712 commented on EducationalPlatform/Attributes/AuthorizationAttribute.cs
> +        public AuthorizationAttribute(params string[] roles) : base(typeof(AuthorizationFilter))
На вообще все методы наши

2021-10-05 09:04 UTC, Egor1712 commented on EducationalPlatform/Attributes/AuthorizationAttribute.cs
> +            if (user.Identity == null || !user.Identity.IsAuthenticated || roles.Any(x => !user.IsInRole(x)))
Понял

2021-10-05 09:23 UTC, AlexeyShirinkin commented on EducationalPlatform/Attributes/AuthorizationAttribute.cs
> +        public AuthorizationAttribute(params string[] roles) : base(typeof(AuthorizationFilter))
То есть чтобы залогинится и зарегистрировать пользователя нужно авторизироваться?)

2021-10-05 10:45 UTC, Egor1712 commented on EducationalPlatform/Attributes/AuthorizationAttribute.cs
> +        public AuthorizationAttribute(params string[] roles) : base(typeof(AuthorizationFilter))
Блин, ну кроме этих)))

2021-10-13 04:52 UTC, merged